---
- name: ensure ssh key exists
  user:  name=root generate_ssh_key=yes ssh_key_file=.ssh/id_rsa

- name: Register SSH key at DigitalOcean
  digital_ocean: state=present command=ssh name=ssh_key ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }} api_token={{ do_token }}
  register: ssh_key
